services:
  - type: web
    name: exam-portal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
